### ISSUE TITLE
get_base_input function needs agreed upon OM values

### ISSUE THREAD

**Issue by gavinfay** [cmlegault/IBMWG#1]
I added [get_base_input()](https://github.com/cmlegault/IBMWG/blob/master/demonstrations/gavin/base_input.R) which creates the `input` object with the agreed 'default' OM settings.

This can then be called by other functions to modify the list for the various scenarios.

SRR parameters not updated yet, didn't get a chance to interpret the parameterization for B-H. Tim/Andy/Chris can you help?

Next step is for Gavin to incorporate this into the retroOM example so we create full base period projection with this workflow for these.

**Comment by cmlegault** [comment]
Tim modified WHAM as OM to use R0 and steepness parameters as input
