### ISSUE TITLE
agg_xxx different sizes

### ISSUE THREAD

**Issue by JDeroba** [cmlegault/IBMWG#11]
in the "y" wham output, y$agg_indices is a different length (# years long) than y$agg_catch.  I thought both would be the same size given that I think they should both contain values from the base period.  This discrepancy caused some indexing and subscript issues.

**Comment by timjmiller** [comment]
The number of rows (# base period years) should be the same for agg_indices and agg_catch. @jonathanderoba can you make an example where they are not?

**Comment by JDeroba** [comment]
My mistake.
