### ISSUE TITLE
Packages being loaded within functions

### ISSUE THREAD

**Issue by gavinfay** [cmlegault/IBMWG#13]
Several instances of dependencies being loaded on the fly in functions.
Probably slows things down for some methods as packages loaded each time the function is called rather than having it loaded to start with.
Not a big problem, just needs some tidying up when linking/reorganizing.
This issue is to remind us (me).

**Comment by cmlegault** [comment]
All library calls in wham_mse_functions.R moved to top of Run_MSE.R. I didn't find any other library calls in code, but good reminder to search for these later to make sure no others slip through.
