### ISSUE TITLE
Added faster version of PlanBsmooth

### ISSUE THREAD

**Issue by gavinfay** [cmlegault/IBMWG#17]
I did some profiling and noticed that a lot of time was being spent in `ApplyPlanBsmooth()`, for printing (warnings) and plotting that is not required in the MSE.

e.g.
![image](https://user-images.githubusercontent.com/8093556/90903996-b4721480-e39c-11ea-89b2-c44011c716ec.png)

I copied the function code into a new function and commented out the printing and plotting. This results in about 5x faster code and R is spending most of its time in the OM now instead of in the `ApplyPlanBsmooth()` function. (40ms instead of 22660ms).

![image](https://user-images.githubusercontent.com/8093556/90904153-e8e5d080-e39c-11ea-8d7d-89ac00af8cf3.png)

Interestingly, I initially created a change within the PlanBSmooth package itself (my forked version), but something was still slowing it down (offender seemed to be the magrittr pipe, unsure if different versions of magrittr are being used). Loading from a separate script instead of using the PlanBsmooth package seemed to do the trick. Code was also slower when function was appended to `wham_mse_functions.R()`.

No changes to computations, just commented out the warnings and the plotting code.

`ApplyPlanBsmooth_fast()` is in `GF_planb.R`.

Recommend that we do some more profiling before starting production runs, to i.d. other potential bottlenecks. (I did not bother trying to see if there were obvious things in the do_wham_mse to suppress, just focused on the IBM here)

**Comment by cmlegault** [comment]
Confirmed GF_planb.R has correct code for PlanBsmooth function. Changed defaults for showplots and showwarn from TRUE to FALSE, just for safety, doesn't change anything in how function operates.
Thanks Gavin for checking for speed bottlenecks!
