### ISSUE TITLE
Frequency of index based assessments?

### ISSUE THREAD

**Issue by rich-bell** [cmlegault/IBMWG#23]
Wondering if there was a decision on how frequently the index based assessments would be run, every two years, three years, etc?
Joe Langan's dynamic linear model function uses a forecasting method to generate the catch advise within specifications.  The function can forecast as many years of catch as needed to cover the time between assessments.  Currently the default is two 
y$JoeDLM_n_ahead<-2 # forecasting 2 years and returning 2 years of catch advice
, but was hoping this could be connected with a higher level control so the implementation of the function does not crash the simulations.

**Comment by cmlegault** [comment]
The default will be to conduct the index based assessments every other year. It would be nice to have the functions generalized to allow easy exploration of conducting assessments every year or every third year, if this isn't too much of a pain.

**Comment by gavinfay** [comment]
This is already specified in the input object `input$adv.yr`. Default is 2 but can be changed by the scenario specifications. This could be passed to `JoeDLM()` to make the forecast reactive. Seems like a low priority at the moment.
