### ISSUE TITLE
M_CC and ExpandSurvey_modified variants

### ISSUE THREAD

**Issue by JDeroba** [cmlegault/IBMWG#26]
Gavin,
So the M_CC and ExpandSurvey_modified IBM functions have sub-options controlled by if statements within the functions.  More specificcally, M_CC needs to be run with 2 different target F approaches, and ExpandSurvey_modified has 4 different F target approaches.  The F target to use is defined in IBM_options.  Can you confirm that the code is ready to somehow run each of these IBM methods with all of the F target variants?  If not, then can you advise me on how to help make that happen?  Seems like these F alternatives might need to be defined in your tibble, but I don't know.

JJD

**Comment by gavinfay** [comment]
Hi Jon,
Yes, these get set using Chris' extended namings when setting up the specifications.
See lines 95-110 or so of [setup_scenarios.R](https://github.com/cmlegault/IBMWG/blob/master/demonstrations/gavin/setup_scenarios.R).
They then get attached to the input object, and then assigned to the `y` after the get.IBM.input() function does its thing (see lines 88-90 of [wham_mse_functions.R](https://github.com/cmlegault/IBMWG/blob/master/demonstrations/gavin/wham_mse_functions.R).
I didn't write the full set of options, this needs cleaning up, but this seems to work for me.

**Comment by JDeroba** [comment]
Sweet.  To avoid confusion, should I delete this specification in the IBM_options() script or hold off until we're ready to hit "go"?
