### ISSUE TITLE
sys.date use means only one run per day?

### ISSUE THREAD

**Issue by cmlegault** [cmlegault/IBMWG#31]
today = format(Sys.Date(), "%Y/%m/%d") is used in the output file naming
outfile = paste0("output/demo-mse-",user,"-",str_remove_all(today,"/"),".rds")
saveRDS(mse_output, file = outfile)
Does this mean that a user can only do one set of simulations per day? It appears that any additional runs done the same day will overwrite the runs already done that day. Or am I missing something? Would using sys.time instead in the outfile name fix this problem, if it is a problem?

**Comment by gavinfay** [comment]
changed to sys.time as suggested during 09/17/2020 call.
