### ISSUE TITLE
error in call to do_wham_mse, 'input' not found

### ISSUE THREAD

**Issue by gavinfay** [cmlegault/IBMWG#33]
An error was being thrown when running the MSE due to an additional argument now being passed to get.IBM.input and IBM.options - to properly pass the assessment frequency to the DLM estimation method.
Argument name was being handled properly.
This is now fixed and the error that @liz-brooks mentioned during the 09-17-2020 call is no longer (at least for @gavinfay ) being generated. Did verify that I reproduced the error before I fixed it, so I think this is good now.

**Comment by timjmiller** [comment]
@gavinfay I get this error when trying to run do_mse after rerunning code to generate objects in rds files:

Error: Problem with `mutate()` input `wham`.
✖ object 'input' not found
ℹ Input `wham` is `furrr::future_pmap(list(seed = .$seed, input = .$input), do_wham_mse_sim)`.

**Comment by timjmiller** [comment]
fixed
