### ISSUE TITLE
new performance metric not working

### ISSUE THREAD

**Issue by cmlegault** [cmlegault/IBMWG#46]
I added SSB/SSBmsy and F/Fmsy to the performance metrics code. The SSB ratio works fine, but the F doesn't. I can't see the problem. Can someone help me find the bug? Thanks!

**Comment by timjmiller** [comment]
Can you describe more what happens exactly? Is there a test we can run to see the problem?

**Comment by cmlegault** [comment]
Sorry, should have been more clear. When I run my version of summarize_results.R, the s_ and l_ avg_f_fmsy metrics are not created, instead a "" metric is. You can test this with any small output rds file.

**Comment by timjmiller** [comment]
Are the other "fmsy" metrics provided by get_F_metrics ok?

**Comment by cmlegault** [comment]
They seem to be, get a range of results across different IBMs.

**Comment by timjmiller** [comment]
So, the "avg" additions to get_F_metrics function were within a list definition and using "<-" doesn't  name those elements of the list. I edited and pushed the change. Should be fine to close this.
