### ISSUE TITLE
apply catch.mult (OFL vs ABC)

### ISSUE THREAD

**Issue by cmlegault** [cmlegault/IBMWG#47]
I think we could do it in the do_wham_mse_sim function. "Just" have to pull the catch.mult out of the input object (line 19?), then apply it to the catch advice (lines 135 and 199? need to be careful to apply to only catch advice, not all the other stuff that gets returned by IBM function). I think this will allow the catch retro source to function correctly. 

Alternatively, could put catch.mult in each of the IBM functions, but this seems more dangerous to me.

**Comment by timjmiller** [comment]
Does someone know that catch.mult is in input?

**Comment by timjmiller** [comment]
I have modified the wham_mse_sim function to apply the catch.mult and tested it with the do_mse_test.R script. It should be safe to open up the 0.75 catch mult scenarios and close this issue.
