### ISSUE TITLE
remove catch.mult=0.75 results so far

### ISSUE THREAD

**Issue by cmlegault** [cmlegault/IBMWG#48]
We now have a bunch of duplicate runs that don't do us any good because catch.mult was not applied (all are catch.mult=1). 

I don't know if it would be easier to change the results or to set up some code to filter out these results and replace them with results from later runs.

**Comment by timjmiller** [comment]
Should be safe to redo the 0.75 catch.mult scenarios now.

**Comment by cmlegault** [comment]
Old runs with catch.mult=0.75 now removed from results in my_summarize_results.R located in demonstrations\chris\demo_plot directory.

**Comment by gavinfay** [comment]
Reinserted the 0.75 catch.mult scenarios into those considered when reviewing which runs to do.

Also filters out the old 075 catch.mult scenarios from the existing results when summarizing in `summarize_results.R` and @cmlegault's `my_summarize_results.R`
