### ISSUE TITLE
replicate scenarios

### ISSUE THREAD

**Issue by cmlegault** [cmlegault/IBMWG#49]
Discovered scenarios.csv has both M_CC and CatchCurve_FequalM IBMs - these are equivalent

result is that iscens 25-32 are the same as 89-96 and iscens 138-145 are the same as 202-209

too late to renumber scenarios
will need to do some filtering to remove replicate runs from results
will need to filter out replicate scenarios from future runs to save time
will need to adjust output tables and plots to deal with the missing scenarios

**Comment by gavinfay** [comment]
Commit @de44288 adds code to `do_mse.R` to filter replicated scenarios when putting the 'todo' list together for new runs.

`dupes <- duplicated(mse_sim_setup[,-(1:2)])`
`not_dupes <- mse_sim_setup$rowid[!dupes]`
.....
`filter(rowid %in% not_dupes) %>% `

**Comment by gavinfay** [comment]
@cmlegault I made some changes to your `my_summarize_results.R` that should help with processing and filter the bad results out.

**Comment by cmlegault** [comment]
Thanks Gavin! Very helpful. I modified demo_make_tables_figures.R as well to use this trick,

**Comment by cmlegault** [comment]
Ran into problems trying to map large numbers of large files in my_summarize_results.R (many GB of data was too much for little laptop to handle all at once). So reverted to looping through runs. Appreciate the hint about map - would be nice if running on network machine with lots of memory.

**Comment by gavinfay** [comment]
Ah yes. Makes sense!

**Comment by cmlegault** [comment]
Looks like we've got everything under control here.
