### ISSUE TITLE
IBS_Functions  - not all IBS methods done yet

### ISSUE THREAD

**Issue by JDeroba** [cmlegault/IBMWG#5]
Be sure to make changes to the index based methods functions within wham_mse_functions.R script.  That script now houses the working versions of the methods functions.
Still need:
-Joe Langan
-Ensemble - need to add the last 1 or 2 index methods to the ensemble function; might just be missing Joe Langan
-Low priority of mean length and FSD methods.

**Comment by cmlegault** [comment]
JoeDLM and ensemble functions added - thanks Joe and Jon!
