### ISSUE TITLE
catch misreporting description

### ISSUE THREAD

**Issue by JDeroba** [cmlegault/IBMWG#54]
I lifted the text describing catch misreporting directly from the final Report, but I think it reads as though we evaluated over-reporting, not under-reporting.  See the "Study Design" section of the pub rmd file for the text that I'm referencing.  "we applied a scalar multiple to the true catch observations...scalar was 5...".  Can someone who knows exactly how this functioned please revise the text?

**Comment by timjmiller** [comment]
Good catch. I fixed the text. Numbers needed to be inverted.
